version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.25-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    network_mode: host

  student-bot:
    build:
      context: .
      dockerfile: DockerfileStudent
    image: student-bot
    container_name: student-bot-container
    restart: always
    network_mode: host

  teacher-bot:
    build:
      context: .
      dockerfile: DockerfileTeacher
    image: teacher-bot
    container_name: teacher-bot-container
    restart: always
    network_mode: host